use Mix.Config

# For production, we configure the host to read the PORT
# from the system environment. Therefore, you will need
# to set PORT=80 before running your server.
#
# You should also configure the url host to something
# meaningful, we use this information when generating URLs.
#
# Finally, we also include the path to a manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.
config :docset_api, DocsetApi.Endpoint,
  http: [port: System.get_env("PORT")],
  url: [host: System.get_env("SECRET_KET_BASE"), port: 80],
  cache_static_manifest: "priv/static/manifest.json"

# Do not print debug messages in production
config :logger, level: :info

config :docset_api, DocsetApi.Endpoint,
  secret_key_base: System.get_env("SECRET_KET_BASE")

config :docset_api,
  tmp_dir: ""
